### ISSUE TITLE
Jest's tests are not working

### ISSUE THREAD

**Issue by Rommyf1** [Rommyf1/Raven-test#1]
The projects' test are not working due to an unknown problem; the error performed is the following:

> 

SyntaxError: Unexpected token ':'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
    at async link (internal/modules/esm/module_job.js:37:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raven_test@1.0.0 test: `jest --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raven_test@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> 

This problem began when I tried to get support to ESM in the tests.

**Comment by Rommyf1** [comment]
Issue was solved
